export const skillsData = [
  // Frontend Development Skills
  {
    name: 'React.js',
    experience: 'Expert',
    years: '4 years',
    projects: '15+ projects',
    description: 'Building scalable web applications',
    categorySlug: 'frontend-development',
  },
  {
    name: 'Next.js',
    experience: 'Advanced',
    years: '3.5 years',
    projects: '12+ projects',
    description: 'Full-stack React framework',
    categorySlug: 'frontend-development',
  },
  {
    name: 'TypeScript',
    experience: 'Advanced',
    years: '3 years',
    projects: '10+ projects',
    description: 'Type-safe development',
    categorySlug: 'frontend-development',
  },
  {
    name: 'Tailwind CSS',
    experience: 'Advanced',
    years: '2.5 years',
    projects: '8+ projects',
    description: 'Utility-first CSS framework',
    categorySlug: 'frontend-development',
  },
  {
    name: 'HTML/CSS/JS',
    experience: 'Expert',
    years: '4 years',
    projects: '20+ projects',
    description: 'Core web technologies',
    categorySlug: 'frontend-development',
  },
  {
    name: 'Angular',
    experience: 'Intermediate',
    years: '1 year',
    projects: '3+ projects',
    description: 'Enterprise applications',
    categorySlug: 'frontend-development',
  },

  // Backend Development Skills
  {
    name: 'Node.js',
    experience: 'Intermediate',
    years: '1 year',
    projects: '5+ projects',
    description: 'Server-side JavaScript',
    categorySlug: 'backend-development',
  },
  {
    name: 'Express.js',
    experience: 'Intermediate',
    years: '1 year',
    projects: '4+ projects',
    description: 'Web application framework',
    categorySlug: 'backend-development',
  },
  {
    name: 'NestJS',
    experience: 'Intermediate',
    years: '1 year',
    projects: '3+ projects',
    description: 'Scalable server applications',
    categorySlug: 'backend-development',
  },
  {
    name: '.NET',
    experience: 'Beginner',
    years: '6 months',
    projects: '2+ projects',
    description: 'Microsoft ecosystem',
    categorySlug: 'backend-development',
  },

  // Database & Storage Skills
  {
    name: 'MySQL',
    experience: 'Intermediate',
    years: '1 year',
    projects: '6+ projects',
    description: 'Relational database management',
    categorySlug: 'database-storage',
  },
  {
    name: 'MongoDB',
    experience: 'Intermediate',
    years: '8 months',
    projects: '4+ projects',
    description: 'NoSQL document database',
    categorySlug: 'database-storage',
  },
  {
    name: 'PostgreSQL',
    experience: 'Beginner',
    years: '6 months',
    projects: '2+ projects',
    description: 'Advanced SQL database',
    categorySlug: 'database-storage',
  },

  // UI/UX & Tools Skills
  {
    name: 'PrimeNG',
    experience: 'Advanced',
    years: '2 years',
    projects: '8+ projects',
    description: 'Angular UI component library',
    categorySlug: 'ui-ux-tools',
  },
  {
    name: 'Material-UI',
    experience: 'Advanced',
    years: '1.5 years',
    projects: '6+ projects',
    description: 'React component library',
    categorySlug: 'ui-ux-tools',
  },
  {
    name: 'Ant Design',
    experience: 'Intermediate',
    years: '1 year',
    projects: '4+ projects',
    description: 'Enterprise UI design',
    categorySlug: 'ui-ux-tools',
  },
  {
    name: 'Figma',
    experience: 'Intermediate',
    years: '1 year',
    projects: '5+ projects',
    description: 'UI/UX design tool',
    categorySlug: 'ui-ux-tools',
  },
  {
    name: 'Git',
    experience: 'Advanced',
    years: '3 years',
    projects: '20+ projects',
    description: 'Version control system',
    categorySlug: 'ui-ux-tools',
  },
]
